### ISSUE TITLE
icon colour

### ISSUE THREAD

**Issue by akebu6** [Maseho/Maseho#1]
your icons need to have a colour that can easily be visible to those using both dark and light mode. Because for someone like me who is using dark mode, I cannot really make out most of the icons :-)

**Comment by Maseho** [comment]
Definity going to work on that, thank you for the feedback :-)

**Comment by akebu6** [comment]
if it ain't open source, then you are doing it wrong lol. I like thinking about it that way and this is part of the open source and taking feedback

**Comment by akebu6** [comment]
Is this issue still open or has it been fixed so it can be closed?
